name: SQS Integration Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to test'
        required: true
        type: choice
        options:
          - stage
          - prod
        default: 'stage'
      commit_sha:
        description: 'Commit SHA (optional)'
        required: false
        default: ''
  schedule:
    - cron: '0 * * * *'

jobs:
  manual_integration_test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_sha || github.repository_default_branch }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
      
      - name: Execute tests
        run: pytest -s -n auto --ignore=tests/test_syntheic_geo.py
        env:
          SQS_ENVIRONMENTS: ${{ github.event.inputs.environment }}
          SQS_API_KEY: ${{ secrets.SQS_API_KEY }}
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
          
  scheduled_integration_test:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: re-add prod environment ", prod"
        # https://linear.app/osmosis/issue/DATA-198/production-deployment-june-11
        environment: [stage]
      # Do not cancel concurrent jobs in matrix.
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
      
      - name: Execute tests
        run: pytest -s -n auto --ignore=tests/test_syntheic_geo.py
        env:
          SQS_ENVIRONMENTS: ${{ matrix.environment }}
          SQS_API_KEY: ${{ secrets.SQS_API_KEY }}
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
